# Generated by Django 3.2.15 on 2023-06-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0005_auto_20230615_0019"),
    ]

    operations = [
        migrations.RemoveField(model_name="application", name="birthday",),
        migrations.AddField(
            model_name="application",
            name="age",
            field=models.PositiveIntegerField(
                choices=[
                    (18, "18"),
                    (19, "19"),
                    (20, "20"),
                    (21, "21"),
                    (22, "22"),
                    (23, "22+"),
                ],
                default=21,
            ),
            preserve_default=False,
        ),
    ]
