# Generated by Django 3.2.15 on 2023-06-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0006_auto_20230615_0103"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="age",
            field=models.PositiveIntegerField(
                choices=[
                    (None, ""),
                    (18, "18"),
                    (19, "19"),
                    (20, "20"),
                    (21, "21"),
                    (22, "22"),
                    (23, "22+"),
                ]
            ),
        ),
    ]
