# Generated by Django 3.2.15 on 2023-06-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20230615_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='what_past_experience',
            field=models.TextField(blank=True, help_text='If you’ve been to a hackathon, briefly tell us your experience. If not, describe what you expect to see and experience.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='what_technical_experience',
            field=models.TextField(blank=True, help_text='What is your technical experience with software?', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='why_participate',
            field=models.TextField(blank=True, help_text='Why do you want to participate in NewHacks?', max_length=1000, null=True),
        ),
    ]
