# Generated by Django 3.2.15 on 2023-06-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0010_auto_20230615_2143"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="email_agree",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="I authorize MLH to send me occasional emails about relevant events, career opportunities, and community announcements.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="study_level",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("less-than-secondary", "Less than Secondary / High School"),
                    ("secondary", "Secondary / High School"),
                    (
                        "undergraduate-2-year",
                        "Undergraduate University (2 year - community college or similar)",
                    ),
                    ("undergraduate-3-year", "Undergraduate University (3+ year)"),
                    (
                        "graduate",
                        "Graduate University (Masters, Professional, Doctoral, etc)",
                    ),
                    ("code-school", "Code School / Bootcamp"),
                    (
                        "vocational",
                        "Other Vocational / Trade Program or Apprenticeship",
                    ),
                    ("post-doctorate", "Post Doctorate"),
                    ("other", "Other"),
                    ("not-a-student", "I’m not currently a student"),
                    ("no-answer", "Prefer not to answer"),
                ],
                help_text="Level of Study",
                max_length=50,
            ),
        ),
    ]
