# Generated by Django 3.2.15 on 2023-10-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0011_auto_20230627_2303"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="under_age",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
