# Generated by Django 3.2.15 on 2023-10-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0011_auto_20230627_2303"),
    ]

    operations = [
        migrations.AddField(
            model_name="application", name="rsvp", field=models.BooleanField(null=True),
        ),
    ]
