# Generated by Django 3.2.15 on 2023-10-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0012_application_rsvp"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="under_age",
            field=models.BooleanField(default=False),
        ),
    ]
